<a href="https://colab.research.google.com/github/omisssss/automated-recipe-selector-/blob/main/apriory_assing4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("dataset")

dataset

In [ ]:
#viewing the dataset 
import pandas as pd
#import matplotlib.pyplot as plt


spreadsheet = pd.read_csv('/content/Cosmetics - Cosmetics.csv')

spreadsheet

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
0,No,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,No,No,Yes
1,No,No,Yes,No,Yes,No,Yes,Yes,No,No,Yes,Yes,No,No
2,No,Yes,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No
3,No,No,Yes,Yes,Yes,No,Yes,No,No,No,Yes,No,No,Yes
4,No,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,No,Yes,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,No,No,No,No,No,No,No,No,No,No,No,No,No,No
996,No,No,No,No,No,No,No,No,No,No,Yes,Yes,No,No
997,No,Yes,Yes,Yes,Yes,No,No,Yes,No,No,Yes,No,Yes,Yes
998,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,No,No,Yes,Yes
999,No,No,No,No,Yes,No,Yes,Yes,No,Yes,No,No,No,Yes

In [ ]:
#q1  frequnet itemset 
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
tr = TransactionEncoder()
tr_arr = tr.fit(spreadsheet).transform(spreadsheet)
df = pd.DataFrame(tr_arr, columns=tr.columns_)
df

,,B,C,E,F,G,L,M,N,P,...,n,o,p,r,s,t,u,w,y,z
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,True,False,False,False,False,False,False,False,True,True,...,False,True,False,False,True,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,True,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,True,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df = df.dropna()

In [ ]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets = apriori(df, min_support = 0.3, use_colnames = True)
frequent_itemsets

/usr/local/lib/python3.9/dist-packages/mlxtend/frequent_patterns/apriori.py:158: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  itemsets = pd.Series([frozenset(i) for i in itemset_dict[k]])

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [ ]:
df

,,B,C,E,F,G,L,M,N,P,...,n,o,p,r,s,t,u,w,y,z
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,True,False,False,False,False,False,False,False,True,True,...,False,True,False,False,True,False,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,True,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,True,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:

#viewing the dataset 
import pandas as pd
#import matplotlib.pyplot as plt

spreadsheet = pd.read_excel('/content/Cosmetics.xlsx')

spreadsheet

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
0,No,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,No,No,No,No,Yes
1,No,No,Yes,No,Yes,No,Yes,Yes,No,No,Yes,Yes,No,No
2,No,Yes,No,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No
3,No,No,Yes,Yes,Yes,No,Yes,No,No,No,Yes,No,No,Yes
4,No,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,No,Yes,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,No,No,No,No,No,No,No,No,No,No,No,No,No,No
996,No,No,No,No,No,No,No,No,No,No,Yes,Yes,No,No
997,No,Yes,Yes,Yes,Yes,No,No,Yes,No,No,Yes,No,Yes,Yes
998,Yes,Yes,No,No,Yes,No,No,No,Yes,Yes,No,No,Yes,Yes
999,No,No,No,No,Yes,No,Yes,Yes,No,Yes,No,No,No,Yes

In [28]:
spreadsheet=spreadsheet.replace({'Yes':True ,'No' :False })
spreadsheet

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
0,False,True,True,True,True,False,True,True,True,False,False,False,False,True
1,False,False,True,False,True,False,True,True,False,False,True,True,False,False
2,False,True,False,False,True,True,True,True,True,True,True,True,True,False
3,False,False,True,True,True,False,True,False,False,False,True,False,False,True
4,False,True,False,False,True,False,True,True,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,True,True,False,False
997,False,True,True,True,True,False,False,True,False,False,True,False,True,True
998,True,True,False,False,True,False,False,False,True,True,False,False,True,True
999,False,False,False,False,True,False,True,True,False,True,False,False,False,True

In [29]:




from mlxtend.frequent_patterns import apriori, association_rules
spreadsheet
frq_set=apriori(spreadsheet, min_support=0.3,use_colnames=True)
frq_set

   support                 itemsets
0    0.363                  (Blush)
1    0.442              (Concealer)
2    0.357                (Mascara)
3    0.381             (Eye shadow)
4    0.536             (Foundation)
5    0.490              (Lip Gloss)
6    0.322               (Lipstick)
7    0.457               (Eyeliner)
8    0.321    (Mascara, Eye shadow)
9    0.356  (Foundation, Lip Gloss)

In [30]:
rules = association_rules(frq_set, metric ="confidence", min_threshold = 0.7) 
rules = rules.sort_values(['confidence'], ascending =[ False]) 
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Mascara),(Eye shadow),0.357,0.381,0.321,0.899160,2.359999,0.184983,6.138417
1,(Eye shadow),(Mascara),0.381,0.357,0.321,0.842520,2.359999,0.184983,4.083050
2,(Lip Gloss),(Foundation),0.490,0.536,0.356,0.726531,1.355468,0.093360,1.696716